import os
import uuid
import subprocess
from datetime import datetime, timezone
from pathlib import Path

import boto3
from boto3.exceptions import S3UploadFailedError
from botocore.exceptions import BotoCoreError, ClientError
from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from dotenv import load_dotenv


load_dotenv()


app = FastAPI(title="MPI Runner API")

BASE_DIR = Path(__file__).resolve().parent

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.mount("/static", StaticFiles(directory=str(BASE_DIR / "frontend")), name="static")


AWS_REGION = os.getenv("AWS_REGION", "ap-south-1")
S3_BUCKET = os.getenv("S3_BUCKET", "")
MPI_BINARY = os.getenv("MPI_BINARY", "./phase2")
MPI_PROCS = os.getenv("MPI_PROCS", "4")
MPI_OVERSUBSCRIBE = os.getenv("MPI_OVERSUBSCRIBE", "true").lower() in {"1", "true", "yes", "on"}
LOCAL_WORK_DIR = os.getenv("LOCAL_WORK_DIR", "/tmp/mpi_jobs")

if os.path.isabs(MPI_BINARY):
    MPI_BINARY_PATH = MPI_BINARY
else:
    MPI_BINARY_PATH = str((BASE_DIR / MPI_BINARY).resolve())

os.makedirs(LOCAL_WORK_DIR, exist_ok=True)


@app.get("/")
def home():
    return FileResponse(str(BASE_DIR / "frontend" / "index.html"))


@app.get("/health")
def health():
    return {"status": "ok", "time_utc": datetime.now(timezone.utc).isoformat()}


def _run_cmd(command: list[str], timeout_seconds: int = 300):
    return subprocess.run(command, capture_output=True, text=True, timeout=timeout_seconds)


def _upload_to_s3(local_path: str, key: str):
    if not S3_BUCKET:
        return None

    s3 = boto3.client("s3", region_name=AWS_REGION)
    s3.upload_file(local_path, S3_BUCKET, key)
    return f"s3://{S3_BUCKET}/{key}"


@app.post("/run")
async def run_mpi(file: UploadFile = File(...)):
    if not file.filename.lower().endswith(".txt"):
        raise HTTPException(status_code=400, detail="Only .txt file is allowed")

    if not os.path.exists(MPI_BINARY_PATH):
        raise HTTPException(status_code=500, detail=f"MPI binary not found: {MPI_BINARY_PATH}")

    job_id = str(uuid.uuid4())
    input_local = os.path.join(LOCAL_WORK_DIR, f"{job_id}_input.txt")
    output_local = os.path.join(LOCAL_WORK_DIR, f"{job_id}_output.txt")

    content = await file.read()
    with open(input_local, "wb") as f:
        f.write(content)

    # phase2 usage: ./phase2 input.txt output.txt
    cmd = ["mpirun"]
    if MPI_OVERSUBSCRIBE:
        cmd.append("--oversubscribe")
    cmd.extend([
        "-np",
        str(MPI_PROCS),
        MPI_BINARY_PATH,
        input_local,
        output_local,
    ])

    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=300)

        # Auto-retry once with --oversubscribe if slots are insufficient
        if (
            proc.returncode != 0
            and "not enough slots available" in (proc.stderr or "").lower()
            and "--oversubscribe" not in cmd
        ):
            retry_cmd = ["mpirun", "--oversubscribe", "-np", str(MPI_PROCS), MPI_BINARY_PATH, input_local, output_local]
            proc = subprocess.run(retry_cmd, capture_output=True, text=True, timeout=300)
    except subprocess.TimeoutExpired:
        raise HTTPException(status_code=504, detail="MPI job timed out")

    if proc.returncode != 0:
        raise HTTPException(
            status_code=500,
            detail={
                "message": "MPI job failed",
                "stderr": proc.stderr,
                "stdout": proc.stdout,
            },
        )

    if not os.path.exists(output_local):
        raise HTTPException(status_code=500, detail="Output file not generated by MPI program")

    with open(output_local, "r", encoding="utf-8", errors="replace") as f:
        output_text = f.read()

    input_s3 = None
    output_s3 = None
    s3_warning = None
    try:
        input_s3 = _upload_to_s3(input_local, f"inputs/{job_id}.txt")
        output_s3 = _upload_to_s3(output_local, f"outputs/{job_id}.txt")
    except (BotoCoreError, ClientError, S3UploadFailedError) as e:
        # Keep MPI result successful even when optional S3 archival fails.
        s3_warning = f"S3 upload failed: {str(e)}"

    return {
        "job_id": job_id,
        "return_code": proc.returncode,
        "stdout": proc.stdout,
        "stderr": proc.stderr,
        "output_preview": output_text[:4000],
        "input_s3": input_s3,
        "output_s3": output_s3,
        "s3_warning": s3_warning,
    }


